import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Router } from "express";

/**
 * Read-only access to the research workspace (../research). Nothing here places orders or changes
 * live trading behaviour: it only serves the reports the research scripts have already written.
 */
const RESEARCH = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../research");

function readJson(file: string): any | null {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}

export const researchRouter = Router();

/** Compact summary: verdict inputs, holdout result, paper-trading progress. */
researchRouter.get("/summary", (_req, res) => {
  const reports = path.join(RESEARCH, "reports");
  const holdout = readJson(path.join(reports, "holdout.json"));
  const paper = readJson(path.join(RESEARCH, "paper", "ledger.json"));
  const pre = readJson(path.join(RESEARCH, "registry", "preregistration.json"));
  const finalStatus = readJson(path.join(reports, "final_status.json"));
  if (!holdout && !paper) {
    res.status(404).json({ error: "No research reports found. Run the scripts in research/ first." });
    return;
  }
  res.json({
    holdoutConsumedAt: pre?.holdoutAccessedAt ?? null,
    ensemble: holdout?.ensemble ?? null,
    baselines: holdout?.baselines ?? null,
    finalStatus,
    paper: paper
      ? {
          mode: paper.mode,
          startDay: paper.startDay,
          dataThrough: paper.dataThrough,
          completedTrades: paper.completedTrades,
          requiredTrades: paper.requiredTrades,
          verdictReady: paper.verdictReady,
          ensembleReturnPct: paper.ensemble?.returnPct ?? 0,
          sleeves: (paper.sleeves ?? []).map((s: any) => ({ id: s.id, targets: s.targets, closedTrades: s.closedTrades, returnPct: s.returnPct })),
        }
      : null,
  });
});

/** The self-contained research dashboard page (generated by research/src/report/dashboard.ts). */
researchRouter.get("/dashboard", (_req, res) => {
  const file = path.join(RESEARCH, "reports", "dashboard.html");
  if (!fs.existsSync(file)) {
    res.status(404).type("text/plain").send("Dashboard not generated yet. Run: cd research && node ../backend/node_modules/tsx/dist/cli.mjs src/report/dashboard.ts");
    return;
  }
  res.type("html").send(fs.readFileSync(file, "utf8"));
});

/** The written research report (markdown), if present. */
researchRouter.get("/report", (_req, res) => {
  const file = path.join(RESEARCH, "reports", "RESEARCH_REPORT.md");
  if (!fs.existsSync(file)) {
    res.status(404).type("text/plain").send("Report not generated yet.");
    return;
  }
  res.type("text/markdown").send(fs.readFileSync(file, "utf8"));
});
